var annotated_dup =
[
    [ "FontManager", null, [
      [ "FontManagerException", "class_font_manager_1_1_font_manager_exception.html", "class_font_manager_1_1_font_manager_exception" ]
    ] ],
    [ "SoundManager", null, [
      [ "SoundManagerException", "class_sound_manager_1_1_sound_manager_exception.html", "class_sound_manager_1_1_sound_manager_exception" ]
    ] ],
    [ "A5Exception", "class_a5_exception.html", "class_a5_exception" ],
    [ "Attribute", "struct_attribute.html", "struct_attribute" ],
    [ "CAnswer", "class_c_answer.html", "class_c_answer" ],
    [ "CButton", "class_c_button.html", "class_c_button" ],
    [ "CDialog", "class_c_dialog.html", "class_c_dialog" ],
    [ "CDialogParser", "class_c_dialog_parser.html", "class_c_dialog_parser" ],
    [ "Communication", "class_communication.html", "class_communication" ],
    [ "CReliant", "class_c_reliant.html", "class_c_reliant" ],
    [ "CStatement", "class_c_statement.html", "class_c_statement" ],
    [ "CTransporter", "class_c_transporter.html", "class_c_transporter" ],
    [ "CWindowDialog", "class_c_window_dialog.html", "class_c_window_dialog" ],
    [ "EConversionException", "class_e_conversion_exception.html", "class_e_conversion_exception" ],
    [ "GamePlanetRec", "class_game_planet_rec.html", "class_game_planet_rec" ],
    [ "GameSpecialRec", "class_game_special_rec.html", "class_game_special_rec" ],
    [ "GameStarbaseRec", "class_game_starbase_rec.html", "class_game_starbase_rec" ],
    [ "Message", "class_message.html", "class_message" ],
    [ "Paralax", "class_paralax.html", "class_paralax" ],
    [ "Sector", "class_sector.html", "class_sector" ],
    [ "Slot", "class_slot.html", "class_slot" ],
    [ "SlotManager", "class_slot_manager.html", "class_slot_manager" ],
    [ "SPoint", "struct_s_point.html", "struct_s_point" ],
    [ "Starfleet", "class_starfleet.html", "class_starfleet" ],
    [ "TAnimation", "class_t_animation.html", "class_t_animation" ],
    [ "TBullet", "class_t_bullet.html", "class_t_bullet" ],
    [ "TDestination", "struct_t_destination.html", "struct_t_destination" ],
    [ "TEngine", "class_t_engine.html", "class_t_engine" ],
    [ "TEnterprise", "class_t_enterprise.html", "class_t_enterprise" ],
    [ "TFederation_Ship", "class_t_federation___ship.html", "class_t_federation___ship" ],
    [ "TInventoryItem", "struct_t_inventory_item.html", "struct_t_inventory_item" ],
    [ "TKeyMapper", "class_t_key_mapper.html", "class_t_key_mapper" ],
    [ "TKlingonBC", "class_t_klingon_b_c.html", "class_t_klingon_b_c" ],
    [ "TKlingonBOP", "class_t_klingon_b_o_p.html", "class_t_klingon_b_o_p" ],
    [ "TMenu", "class_t_menu.html", "class_t_menu" ],
    [ "TMenuItem", "class_t_menu_item.html", "class_t_menu_item" ],
    [ "TParticle", "class_t_particle.html", "class_t_particle" ],
    [ "TProbe", "class_t_probe.html", "class_t_probe" ],
    [ "TRomulanBop", "class_t_romulan_bop.html", "class_t_romulan_bop" ],
    [ "TScanInfo", "struct_t_scan_info.html", "struct_t_scan_info" ],
    [ "TShip", "class_t_ship.html", "class_t_ship" ],
    [ "TSpaceObject", "class_t_space_object.html", "class_t_space_object" ],
    [ "TSprite", "class_t_sprite.html", "class_t_sprite" ],
    [ "TStar", "struct_t_star.html", "struct_t_star" ],
    [ "TStarbase", "class_t_starbase.html", "class_t_starbase" ],
    [ "Universe", "class_universe.html", "class_universe" ],
    [ "XMLParser", "class_x_m_l_parser.html", "class_x_m_l_parser" ]
];